### ISSUE TITLE
第十章Optional的空指针异常报错是为什么？

### ISSUE THREAD

**Issue by guanpengchn** [NGLSL/Java8InAction-ReadingNotes#1]
您好，最近在看java 8这本书，遇到了问题想和您讨论下，问题如下：

第十章Optional的flatMap存在NullPointerException错误，具体代码如下：

```java
import java.util.Optional;

public class test2 {
  public static class Car {
    public Optional<Insurance> insurance;

    public Optional<Insurance> getInsurance() {
      return insurance;
    }
  }

  public static class Insurance {
    public String name;

    public String getName() {
      return name;
    }
  }

  public static class Person {
    public Optional<Car> car;

    public Optional<Car> getCar() {
      return car;
    }
  }
  public static String getCarInsuranceName(Optional<Person> person) {
    return person.flatMap(Person::getCar)
            .flatMap(Car::getInsurance)
            .map(Insurance::getName)
            .orElse("Unknown");
  }
  public static void main(String[] args) {
    Person person = new Person();
    Car car = new Car();
    Insurance insurance = new Insurance();
//    insurance.name = "test";
//    car.insurance = Optional.of(insurance);
    person.car = Optional.of(car);
    String result= getCarInsuranceName(Optional.of(person));
    System.out.println(result);
  }
}
```

命令行日志：

```
Exception in thread "main" java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at java.util.Optional.flatMap(Optional.java:241)
	at test2.getCarInsuranceName(test2.java:29)
	at test2.main(test2.java:41)
```

Optional我认为是避免NullPointerException的，在测试map的时候是没有错误的，返回了Unknown，但是flatMap为空时异常出现，没有返回Unknown，麻烦有空解答一下

**Comment by guanpengchn** [comment]
打扰了，我已经解决了，[解决方案](https://stackoverflow.com/questions/53679130/optional-flatmap-in-java-has-nullpointerexception?noredirect=1#comment94217151_53679130)，书上的例子是在模仿oracle的官方文档，但是实际工程中不应该把Optional用在传入参数上，翻译了[一篇文章](https://juejin.im/post/5c0b63336fb9a049f43b221b)有讲
